baseline                   https://github.com/qualcomm-linux/kernel-topics.git       linux-next
early/hwe/shikra/dt        https://github.com/qualcomm-linux/kernel-topics.git       early/hwe/shikra/dt
early/hwe/shikra/drivers   https://github.com/qualcomm-linux/kernel-topics.git       early/hwe/shikra/drivers
