name: Post Check Run

description: Posts a GitHub Check Run after uploading artifacts to S3

inputs:
  sha:
    description: SHA of the commit to check
    required: true
  repo:
    description: GitHub repository (owner/repo)
    required: true
  s3_location:
    description: S3 location for the artifacts
    required: true
  APPID:
    description: GitHub App ID
    required: true
  PVK:
    description: GitHub App private key
    required: true
  workflow_name:
    description: Workflow name to post check_run
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate access token
      uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ inputs.APPID }}
        private-key: ${{ inputs.PVK }}
        owner: ${{ github.repository_owner }}

    - name: Post check run
      shell: bash
      run: |
        set -e

        HEAD_SHA="${{ inputs.sha }}"
        ACCESS_TOKEN="${{ steps.app-token.outputs.token }}"
        s3_location="${{ inputs.s3_location }}"
        REPO="${{ inputs.repo }}"
        workflow_name="${{ inputs.workflow_name }}"

        echo "Creating check run for workflow : $workflow_name and commit: $HEAD_SHA"

        if [ "$workflow_name" = "pre_merge" ] || [ "$workflow_name" = "pre_merge_ubuntu" ] || [ "$workflow_name" = "pre_merge_yocto" ]; then
          post_name="Artifacts for ${{ inputs.workflow_name }} uploaded to S3"
          title="Check S3 Location"
          text=$s3_location
        elif [ "$workflow_name" = "Kernel Checkers" ]; then
          post_name="Kernel Checkers passed"
          echo "$post_name"
          title="Kernel checker"
          text=""
        fi

        echo "Post name : $post_name"
        echo "Title : $title"

        CHECK_RUN_ID=$(curl -s -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$REPO/check-runs \
          -d '{
            "name": "'"$post_name"'",
            "head_sha": "'"$HEAD_SHA"'",
            "status": "in_progress",
            "output": {
              "title": "'"$title"'",
              "summary": "",
              "text": "'"$text"'"
            }
          }' | jq -r '.id')

          if [ -z "$CHECK_RUN_ID" ]; then
            echo "Failed to create check run. Exiting."
            exit 1
          fi

        echo "Check run created with ID: $CHECK_RUN_ID"

        echo "Updating check run to completed status..."
        curl -s -L -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$REPO/check-runs/$CHECK_RUN_ID \
          -d '{
            "name": "'"$post_name"'",
            "head_sha": "'"$HEAD_SHA"'",
            "status": "completed",
            "conclusion": "success",
            "output": {
              "title": "'"$title"'",
              "summary": "",
              "text": "'"$text"'"
            }
          }'

        echo "Check run updated successfully for $workflow_name"
