name: Flat Meta Generation

inputs:
  workspace_path:
    description: Workspace path
    required: true
  s3_bucket:
    description: S3 bucket name
    required: true
  docker_image:
    description: Docker image name
    required: true
  rootfs_matrix:
    description: Rootfs matrix
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Flat META
      shell: bash
      run: |
        set -x
        workspace="${{ inputs.workspace_path }}"
        s3_bucket="${{ inputs.s3_bucket }}"
        docker_image="${{ inputs.docker_image }}"
        rootfs_matrix='${{ inputs.rootfs_matrix }}'

        for row in $(echo "$rootfs_matrix" | jq -c '.[]'); do
          machine=$(echo "$row" | jq -r '.machine')
          rootfs=$(echo "$row" | jq -r '.rootfs')
          firmwareid=$(echo "$row" | jq -r '.firmwareid')

          echo "Target : $machine"
          echo "Rootfs ID : $rootfs"
          echo "Firmware ID : $firmwareid"
          echo "-----------------------------"

          if [ -z "$rootfs" ]; then
            echo "No Rootfs present for $target, skip generating Flat Build."
            continue
          fi

          build_dir="$workspace/../flatbuild-$rootfs"
          meta_dir="$build_dir/qcom-multimedia-image-${rootfs}.rootfs.qcomflash"

          artifacts_dir="$build_dir/artifacts"

          mkdir -p "$build_dir"
          cd "$build_dir"
          aws s3 cp s3://$s3_bucket/qualcomm-linux/kernel/meta-qcom/artifacts/qcom-multimedia-image-${rootfs}.rootfs.qcomflash.tar.gz .
          
          mkdir -p $meta_dir
          tar -xzf qcom-multimedia-image-${rootfs}.rootfs.qcomflash.tar.gz --strip-components=1 -C $meta_dir

          cd "$meta_dir"
          sed -i '/rootfs.img/d' rawprogram0.xml

          mkdir -p "$artifacts_dir"
          cd "$artifacts_dir"

          aws s3 cp "s3://$s3_bucket/qualcomm-linux/kernel/meta-qcom/artifacts/initramfs-kerneltest-full-image-qcom-armv8a.cpio.gz" .

          if [ -n "$firmwareid" ]; then
            gunzip -c initramfs-kerneltest-full-image-qcom-armv8a.cpio.gz > kerneltest.cpio
            aws s3 cp "s3://$s3_bucket/qualcomm-linux/kernel/meta-qcom/artifacts/initramfs-firmware-$firmwareid-image-qcom-armv8a.cpio.gz" .
            gunzip -c initramfs-firmware-$firmwareid-image-qcom-armv8a.cpio.gz > firmware.cpio
            cat kerneltest.cpio firmware.cpio > initramfs-$machine.cpio
            gzip initramfs-$machine.cpio
          else
            echo "Firmware not available for Target : $machine"
            mv initramfs-kerneltest-full-image-qcom-armv8a.cpio.gz initramfs-$machine.cpio.gz
          fi

          (cd "$workspace/../kobj/tar-install" && find lib/modules | cpio -o -H newc -R +0:+0 | gzip -9 >> "$artifacts_dir/initramfs-$machine.cpio.gz")

          wget -O systemd-boot-efi.deb http://ports.ubuntu.com/pool/universe/s/systemd/systemd-boot-efi_255.4-1ubuntu8_arm64.deb
          dpkg-deb -xv systemd-boot-efi.deb systemd

          cd "$build_dir"
          docker run -i --rm \
            --user "$(id -u):$(id -g)" \
            --workdir="$PWD" \
            -v "$(dirname "$PWD")":"$(dirname "$PWD")" \
            -e machine="$machine" \
            "$docker_image" bash -c '
              generate_boot_bins.sh efi \
                --ramdisk artifacts/initramfs-$machine.cpio.gz \
                --systemd-boot artifacts/systemd/usr/lib/systemd/boot/efi/systemd-bootaa64.efi \
                --stub artifacts/systemd/usr/lib/systemd/boot/efi/linuxaa64.efi.stub \
                --linux ../kobj/arch/arm64/boot/Image \
                --cmdline "console=ttyMSM0,115200n8 earlycon qcom_geni_serial.con_enabled=1 qcom_scm.download_mode=1 reboot=panic_warm panic=-1 mitigations=auto" \
                --output images
            '

          docker run -i --rm \
            --user "$(id -u):$(id -g)" \
            --workdir="$PWD" \
            -v "$(dirname "$PWD")":"$(dirname "$PWD")" \
            "$docker_image" bash -c "
              generate_boot_bins.sh dtb \
                --input ../kobj/arch/arm64/boot/dts/qcom/$machine.dtb \
                --output images
            "

          cp "$build_dir/images/efi.bin" "$meta_dir"
          cp "$build_dir/images/dtb.bin" "$meta_dir"
          tar -czvf "$workspace/qcom-multimedia-image-${rootfs}.rootfs.qcomflash.tar.gz" "qcom-multimedia-image-${rootfs}.rootfs.qcomflash/"
        done
