name: automerge  

on: 
  workflow_dispatch


jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Clone repositories
        run:  |
             echo Hello, world!
             cd ..
             # git clone https://github.com/sgaud-quic/automerge.git
             # git clone https://github.com/sgaud-quic/kernel-topics.git
             cd kernel-topics
             ../automerge/ci-merge -f ../kernel-config/qcom-next.conf -t head -n -i qcom-next | tee ../merge.log
             cp ../merge.log qcom-next/
             git add qcom-next/merge.log qcom-next/topic_SHA1
             git commit -m "Add qcom-next log files for $(date '+%Y%m%d')"
             git remote add sgaud-quic https://github.com/sgaud-quic/kernel.git
             git fetch sgaud-quic
             git push sgaud-quic HEAD:qcom-next-staging -f
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
